name: Check UUPDUMP
run-name: Check UUPDUMP ${{ inputs.DatabaseOnly == true && '(DatabaseOnly)' || '' }}

on:
  schedule:
    # 每12小时运行一次，在第20分钟，从04:00开始
    - cron: "20 4/12 * * *"
  workflow_dispatch:
    inputs:
      DatabaseOnly:
        description: "仅更新数据"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  actions: write

jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # - name: Change DNS Server
      #   shell: pwsh
      #   run: |
      #     $newDnsServers = @('1.1.1.1', '8.8.8.8')
      #     $networkAdapters = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }
      #     foreach ($adapter in $networkAdapters) {
      #          try {
      #             Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ResetServerAddresses
      #             Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ServerAddresses $newDnsServers
      #         } catch {
      #             Write-Host "为适配器 $($adapter.Name) 设置 DNS 失败: $_"
      #         }
      #     }
      #     ipconfig /flushdns

      # - name: Install Cloudflare WRAP
      #   shell: pwsh
      #   run: |
      #     Write-Host "正在安装 Cloudflare WARP..."
      #     Invoke-WebRequest -Uri "https://1111-releases.cloudflareclient.com/win/latest" -OutFile "C:\cfwarp.msi"
      #     Start-Process "msiexec.exe" -ArgumentList "/i C:\cfwarp.msi /qn" -Wait
      #     . "C:\Program Files\Cloudflare\Cloudflare WARP\warp-cli.exe" registration new
      #     . "C:\Program Files\Cloudflare\Cloudflare WARP\warp-cli.exe" connect
      #     # 添加循环等待连接状态
      #     for ($attemptCount = 0; $attemptCount -lt 10; $attemptCount++) {
      #         $output = . "C:\Program Files\Cloudflare\Cloudflare WARP\warp-cli.exe" status
      #         Write-Host $output
      #         if ($output -like "*Status update: Connected*") {
      #             break
      #         }
      #         Start-Sleep -Seconds 5  # 等待5秒后再次检查
      #     }
      #     if ($attemptCount -eq 10) {
      #         Write-Host "10次尝试后连接失败。"
      #         exit 1  # 以错误码退出
      #     }

      - name: Small Task
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.RCLONE_TOKEN }}
        run: |
          .\.github\workflows\check.ps1 ${{ inputs.DatabaseOnly == true && '-DatabaseOnly' || '' }}

      # - name: Disconnect Cloudflare WRAP
      #   shell: pwsh
      #   run: |
      #       if (Test-Path "C:\Program Files\Cloudflare\Cloudflare WARP\warp-cli.exe") {
      #           try {
      #               . "C:\Program Files\Cloudflare\Cloudflare WARP\warp-cli.exe" disconnect
      #           }
      #           catch {
      #               Write-Warning "断开 Cloudflare WARP 失败"
      #           }
      #       }

      - name: Commit and Push Changes
        shell: pwsh
        run: |
          git add State.yml
          git diff --cached --quiet
          if ($LASTEXITCODE -eq 1) {
            git commit -m "Update State.yml $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
            if ($LASTEXITCODE -ne 0) {
              exit $LASTEXITCODE
            }
            git push
            if ($LASTEXITCODE -ne 0) {
              exit $LASTEXITCODE
            }
          } elseif ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
          }
