name: 在 Windows 上测试 PowerShell
on: workflow_dispatch

jobs:
  pester-test:
    name: Pester 测试
    runs-on: windows-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v6
      - name: 从 Tests.ps1 文件执行 Pester 测试
        shell: pwsh
        run: |
          Invoke-Pester -Passthru
